### ISSUE TITLE
TFLearn v0.2

### ISSUE THREAD

**Issue by aymericdamien** [tflearn/tflearn#50]
Here are some development directions for the next version of TLearn:

- [x] More docs (see #41)
- [x] Add data preprocessing and augmentation (see #66)
- [x] Data Flow with Pipelining for faster data processing ~~and TF Records support~~ (see #66) (TFRecords moved to v0.3)
- [x] Layers can accept functions as argument (c.f. activation=custom_activ_fn, loss=custom_loss_fn, etc...)
- [x] Add more exceptions (See #51 for notebook related errors)
- [ ] Finish tests (+ Travis integration)
- [ ] Add attention module (See below)

Any other ideas are welcome :)

**Comment by daviddao** [comment]
- +1 for data augmentation ! 
- A macrobatching function like in [neon](http://neon.nervanasys.com/docs/latest/loading_data.html#macrobatching) would also be neat. 
- Regarding additional layers, I could also try to adapt my [attention module](https://github.com/tensorflow/models/tree/master/transformer) (spatial transformer network) if there is interest! 
- Finally, implementing residual dropout in tflearn would be awesome!

@aymericdamien What do you think about those ideas?

**Comment by aymericdamien** [comment]
@daviddao thanks for the feedback. 
- Adding attention module would be really awesome I think, you can go ahead :)
- About macrobatching, I believe it is kind of related to the pipeline I am currently working on to speed-up data processing (cf [TensorFlow pipeline](https://www.tensorflow.org/versions/r0.8/how_tos/reading_data/index.html#creating_threads_to_prefetch_using_queuerunner_objects)), I will check it more in depth.
- Residual dropout is also a great feature that should be integrated to TFLean. So we can also work on it if we have enough time, otherwise implement it in a further release.

**Comment by aymericdamien** [comment]
For 'Data Preprocessing and Augmentation', see #66 
For 'More Docs and Tutorials', see #74

**Comment by aymericdamien** [comment]
Released v0.2.0, incomplete milestones moved to next version.
